# Generated by Django 5.1.3 on 2024-11-30 20:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_customer_profile_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('product_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
